name: Deploy to Vercel (manual-only)

on:
  # Disable automatic deploys from GitHub Actions.
  # We use Vercel Git Integration as the source of truth for production deploys.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  note:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Manual deploy only. Use Vercel Git Integration for automatic builds from 'main'."
